#############################
# AstralNetwork Core Config #
#   Made by: Simon_Xz#2982  #
#############################

server-name: "&a&lAstral&f&lNetwork&e"
server-website: "&eAstralNetwork.net"
server-donate: "&ebuy.AstralNetwork.net"
server-discord: "&ediscord.gg/AstralNetwork"