  name: ANPrisonCore
  main: net.astralnetwork.play.Main
  version: 1.0
  commands:
      help:
          usage: /help
          description: displays the help gui.
      list:
        usage: /list
        description: displays custom list.
      anreload:
        usage: /anreload
        description: reloads the config.
      rankup:
        usage: /rankup
        description: Rankup through the prison ranks.
  softdepend:
    - PlaceholderAPI
    - Vault